"""empty message

Revision ID: 1f5ef409dc1d
Revises: 5309ff7abcea
Create Date: 2020-11-03 09:02:03.264348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5ef409dc1d'
down_revision = '5309ff7abcea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###
