"""empty message

Revision ID: 5362b28a02b6
Revises: 
Create Date: 2020-11-06 13:17:19.250263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5362b28a02b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=120), nullable=True),
    sa.Column('email_id', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=120), nullable=False),
    sa.Column('twitter_id', sa.String(length=120), nullable=True),
    sa.Column('about', sa.String(length=240), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email_id'), 'user', ['email_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
